name: simple_dart_table
description: Table Component
version: 0.0.5
repository: https://github.com/simple-dart/table
platforms:
  web:

environment:
  sdk: '>=2.18.0 <3.0.0'


dependencies:
  simple_dart_image: ^0.0.1
  simple_dart_label: ^0.0.1
  simple_dart_link: ^0.0.1
  simple_dart_ui_core: ^0.0.2
  simple_dart_utils_date_time: ^0.0.1
